### PR TITLE
add pkg packages

### PR DESCRIPTION
**Pull request by n1ru4l**
this pr adds the `pkg` and `pkg-fetch` packages into this repository. This allows us to modify and publish them ourselves.

Right now I prefixed the package names with `@org-scope/PACKAGE_NAME` but we might wanna choose a different name when actually publishing them to npm.

### CODE REVIEW

**Review by robertsLando — APPROVED** [review]
LGTM :rocket:

**Comment by robertsLando** [comment]
@n1ru4l Would you create a separete pr for dockerfile changes?

**Comment by n1ru4l** [comment]
@robertsLando Any idea for our naming? We could either create an npm org or user your user name or mine or no org and just call it like pkg-x or pkg-fetch-x?

**Comment by robertsLando** [comment]
I would create an org both in github and on npm. Are you +1?

**Comment by robertsLando** [comment]
@n1ru4l ping :)

**Comment by n1ru4l** [comment]
@robertsLando I agree!

**Comment by n1ru4l** [comment]
We don't necessarily need an org I guess `@yao-pkg/pkg` is a bit redundant. If we would go that way I would recommend renaming the packages to sth like `@yao-pkg/bundler` and `@yao-pkg/binary-fetcher`

**Comment by robertsLando** [comment]
ok let's do it! :+1:

**Comment by n1ru4l** [comment]
@robertsLando Busy this week, will try do get something done on the weekend :)

**Comment by robertsLando** [comment]
No worries @n1ru4l :)

**Comment by robertsLando** [comment]
@n1ru4l News?

**Comment by n1ru4l** [comment]
@robertsLando I am currently pretty busy with other stuff :( I hope I can pick that up again soon!

**Comment by robertsLando** [comment]
@n1ru4l No problem, me too :(

**Pull request closed without merging**
